services:
  app:
    build:
      context: ./docker/java
      dockerfile: Dockerfile
    
    volumes:
      # ワークスペースをマウント
      - ../..:/workspace:cached
      
      # Git設定を保持
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      - ~/.ssh:/home/vscode/.ssh:ro
      
      # Gradleキャッシュを保持
      - gradle-cache:/home/vscode/.gradle

    # ポートフォワーディング
    ports:
      - "8080:8080"
    
    # 環境変数
    environment:
      - JAVA_HOME=/usr/local/openjdk-21
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_NAME=devdb
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
    
    # 作業ディレクトリ
    working_dir: /workspace
    
    # コンテナを起動し続ける
    command: sleep infinity
    
    # ネットワーク設定
    networks:
      - dev-network
    
    # SQL Serverが起動するまで待機
    depends_on:
      sqlserver:
        condition: service_started  # または service_healthy
        required: true

  # SQL Server サービス（Dockerfileを使用）
  sqlserver:
    build:
      context: ./docker/sqlserver
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./docker/sqlserver/init:/docker-entrypoint-initdb.d
    command: ["/bin/bash", "-c", "chmod +x /docker-entrypoint-initdb.d/entrypoint.sh && /docker-entrypoint-initdb.d/entrypoint.sh"]
    networks:
      - dev-network

volumes:
  gradle-cache:
  sqlserver-data:

networks:
  dev-network:
    driver: bridge